#!/bin/bash
#PBS -N SimUpdate8
#PBS -W group_list=mfh
#PBS -q standard
#PBS -J 1-1010
#PBS -l cput=05:00:00
#PBS -l walltime=05:00:00
#PBS -l select=1:ncpus=1:mem=6gb
#PBS -l place=pack:shared
#PBS -j oe

module load python/2/2.7.11

CHR=8

cd $PBS_O_WORKDIR

PBS_ID=$(echo ${PBS_JOBID} | cut -d '[' -f1)
echo "PBS_ID: ${PBS_ID}"

for OBS in {1..100}
do
    BUCKET_OUT_PATH=/rsgrps/mfh4/Ariella/SimPrily_update/obs${OBS}/chr${CHR}
    echo "BUCKET_OUT_PATH: ${BUCKET_OUT_PATH}"
    mkdir -p ${BUCKET_OUT_PATH}

    RUN_DIR=/xdisk/agladstein/SimPrily_update
    cd $RUN_DIR

    for i in {1..10}
    do
        JOB_ID=${PBS_ID}_${PBS_ARRAY_INDEX}_${i}
        echo "JOB_ID: ${JOB_ID}"

        echo "~/env/macss_env_ocelote_2.7.11/bin/python simprily.py -m update_test/input_files/model_chr${CHR}.csv -p update_test/input_files/obs${OBS}/param_chr${CHR}.txt -g genetic_map_b37/genetic_map_GRCh37_chr${CHR}.txt.macshs -i ${JOB_ID} -o ${BUCKET_OUT_PATH} -v"
        ~/env/macss_env_ocelote_2.7.11/bin/python simprily.py -m update_test/input_files/model_chr${CHR}.csv -p update_test/input_files/obs${OBS}/param_chr${CHR}.txt -g genetic_map_b37/genetic_map_GRCh37_chr${CHR}.txt.macshs -i ${JOB_ID} -o ${BUCKET_OUT_PATH} -v
    done
done