#!/bin/bash
#PBS -N SimUpdate1
#PBS -W group_list=mfh
#PBS -q standard
##PBS -J 1-1000
#PBS -J 1-10
#PBS -l cput=00:10:00
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1:mem=6gb
#PBS -l place=pack:shared
#PBS -j oe

module load python/2/2.7.11

cd $PBS_O_WORKDIR

PBS_ID=$(echo ${PBS_JOBID} | cut -d '[' -f1)
echo "PBS_ID: ${PBS_ID}"

JOB_ID=${PBS_ID}_${PBS_ARRAY_INDEX}
echo "JOB_ID: ${JOB_ID}"

BUCKET_OUT_PATH=/rsgrps/mfh4/Ariella/SimPrily_update/chr1
echo "BUCKET_OUT_PATH: ${BUCKET_OUT_PATH}"
mkdir -p ${BUCKET_OUT_PATH}

RUN_DIR=/xdisk/agladstein/SimPrily_update

cd $RUN_DIR

echo "~/env/macss_env_ocelote_2.7.11/bin/python simprily.py"