#!/bin/bash
#PBS -N ABC9
#PBS -W group_list=mfh
#PBS -q standard
#PBS -l cput=01:00:00
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=1:mem=6gb
#PBS -l place=pack:shared
#PBS -j oe

module load python/2/2.7.11
module load R

cd $PBS_O_WORKDIR

BUCKET_OUT_PATH=/rsgrps/mfh4/Ariella/SimPrily_update/chr9
echo "BUCKET_OUT_PATH: ${BUCKET_OUT_PATH}"
mkdir -p ${BUCKET_OUT_PATH}

RUN_DIR=/home/u15/agladstein/SimPrily_update

cd $RUN_DIR

echo "~/env/macss_env_ocelote_2.7.11/bin/python update_test/ABC_update_wf.py ${BUCKET_OUT_PATH} update_test/input_files/param_chr9.txt 10"
~/env/macss_env_ocelote_2.7.11/bin/python update_test/ABC_update_wf.py ${BUCKET_OUT_PATH} update_test/input_files/param_chr9.txt 10
